---

- name: Install Samba, etc.
  apt:
    state: latest
    name:
      - samba
      - winbind
      - libpam-winbind
      - libnss-winbind
      - cifs-utils
      - krb5-user
      - libpam-krb5
      - autofs
      - smbclient

- name: Setup Kerberos
  copy:
    src: krb5.conf
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '0644'

- name: Create NETID homedir directory
  file:
    path: /home/NETID
    state: directory
    mode: '0711'

- name: Enable mkhomedir
  command: /usr/sbin/pam-auth-update --enable mkhomedir

- name: Configure autofs
  copy:
    src: auto.u_drive
    dest: /etc/auto.u_drive
    owner: root
    group: root
    mode: '0755'

- name: Configure autofs
  copy:
    src: u_drive.autofs
    dest: /etc/auto.master.d/u_drive.autofs
    owner: root
    group: root
    mode: '0644'

- name: Restart autofs
  systemd:
    state: restarted
    name: autofs

- name: Reset home directory permissions
  copy:
    src: set_homedir_perms
    dest: /etc/cron.daily/set_homedir_perms
    owner: root
    group: root
    mode: '0755'
